FirstWebApplication/Controllers/UserLoginController.cs
using FirstWebApplication.Models;
using FirstWebApplication.Utils;
using NLog;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Management;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.WebPages;

namespace FirstWebApplication.Controllers
{
    public class UserLoginController : Controller
    {
        #region private readonly variables
        private readonly RestaurantEntities restaurantEntities = new RestaurantEntities();
        private readonly Logger logger = LogManager.GetCurrentClassLogger();
        #endregion

        // GET: StudentLogin

        #region index method return login view
        public ActionResult Index()
        {
            SetSession();
            ViewBag.ReisterMessage = TempData["ReisterMessage"];
            ViewBag.ForgotPassword = TempData["ForgotPassword"];
            ViewBag.PasswordReset = TempData["PasswordReset"];

            return View();
        }
        #endregion

        #region logout method
        public ActionResult LogOut()
        {
            SetSession();
            return RedirectToAction("Index");
        }
        #endregion

        #region User login method
        [HttpPost]
        public ActionResult Login(UserLogin userLogin)
        {
            try
            {
                //check model state is valid
                if (ModelState.IsValid)
                {
                    //get user details from DB
                    UserRegistration user = restaurantEntities.UserRegistrations.Where(s => s.UserName == userLogin.UserName).FirstOrDefault();
                    var dec = Cryptography.DecryptPassword(user.Password);
                    //check user exist, password match, user is verified
                    if (user != null && Cryptography.DecryptPassword(user.Password) == userLogin.Password && user.IsVerified == true)
                    {
                        
                        //set the session 
                        Session["UserID"] = user.UserID.ToString();
                        Session["UserName"] = user.UserName;

                        //redirect to dashboard
                        return RedirectToAction("DashBoard");
                    }
                    //if user doesn't exist
                    else if (user == null)
                    {
                        //redirect to login page with message
                        TempData["ErrorMessage"] = "User not Exist..";
                        return View("Index");
                    }
                    //if user is not verified
                    else if (user.IsVerified == false)
                    {
                        //redirect to login page with message
                        TempData["ErrorMessage"] = "Account is not Verified..";
                        return View("Index");
                    }
                    else 
                    {
                        //return the error view with message
                        TempData["ErrorMessage"] = "Password is incorrect..";
                        return View("Index");
                    }
                     
                    
                }
                //if model is invalid redirect to login page
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                //log the error message in log file
                logger.Error(ex, "UserLoginController Login[Post] Action");

                //return the error view with message
                ViewBag.errorMessage = "Something went wrong please try again..";
                return View("Error");
            }
        }
        #endregion

        #region DashBoard method
        public ActionResult DashBoard(int? page)
        {
            //check user login or not
            if (Session["UserName"] == null)
            {
                //if user not login redirect to error page with message
                ViewBag.errorMessage = "Please Login to continue...";
                return View("Error");
            }
            try
            {
                //get meal type from database 
                ViewBag.mealTypes = GetMealTypesList();
                ViewBag.Action = "DashBoard";

                //add messages to viewbag

                ViewBag.deleteMessage = TempData["DeleteMessage"];

                ViewBag.addMessage = TempData["addMessage"];

                ViewBag.editMessage = TempData["editMessage"];


                //get menu details from DB and return dashboard view
                var menu = restaurantEntities.MenuDetails.OrderByDescending(item => item.CreatedOn).ToList().ToPagedList(page ?? 1, 6);
                return View(menu);
            }
            catch (Exception ex)
            {
                //log the error message in log file
                logger.Error(ex, "UserLoginController DashBoard Action");

                //return the error view with message
                ViewBag.errorMessage = "Something went wrong please try again..";
                return View("Error");
            }
        }
        #endregion

        #region search method 
        public ActionResult SearchFunction(int? MealType, string searchString, int? page)
        {
            //check user login or not
            if (Session["UserName"] == null)
            {
                ViewBag.errorMessage = "Please Login to continue...";
                return View("Error");
            }
            try
            {
                //get meal type from DB
                ViewBag.mealTypes = GetMealTypesList();
                ViewBag.Action = "SearchFunction";

                //return menu details list based on search input and return dashboard view

                //without search anything
                if (MealType == null && (searchString == null || searchString.IsEmpty()))
                {
                    return RedirectToAction("DashBoard");
                }
                //search by name
                else if (MealType == null)
                {
                    var menu = restaurantEntities.MenuDetails.Where(s => s.Name.Contains(searchString)).OrderByDescending(item => item.CreatedOn).ToList().ToPagedList(page ?? 1, 6);
                    return View("DashBoard", menu);
                }
                //search by meal type
                else if (searchString == null || searchString.IsEmpty())
                {
                    var menu = restaurantEntities.MenuDetails.Where(s => s.TypeID == MealType).OrderByDescending(item => item.CreatedOn).ToList().ToPagedList(page ?? 1, 6);
                    return View("DashBoard", menu);
                }
                //search by meal type and name both
                else
                {
                    var menu = restaurantEntities.MenuDetails.Where(s => s.TypeID == MealType).Where(s => s.Name.Contains(searchString)).OrderByDescending(item => item.CreatedOn).ToList().ToPagedList(page ?? 1, 6);
                    return View("DashBoard", menu);
                }
            }
            catch (Exception ex)
            {
                //log the error message in log file
                logger.Error(ex, "UserLoginController SearchFunction Action");

                //return the error view with message
                ViewBag.errorMessage = "Something went wrong please try again..";
                return View("Error");
            }
        }
        #endregion

        #region error page method
        public ActionResult Error()
        {
            return View();
        }
        #endregion

        #region clear user session
        private void SetSession()
        {
            Session["UserName"] = null;
            Session["UserID"] = null;
        }
        #endregion

        #region select list of meal type from DB
        private SelectListItem[] GetMealTypesList()
        {
            SelectListItem[] mealTypes = null;

            //get meal type from DB
            var items = restaurantEntities.MealTypes.Select(a => new SelectListItem()
            {
                Text = a.MealType1,
                Value = a.TypeID.ToString()
            }).ToList();

            mealTypes = items.ToArray();


            // Have to create new instances via projection
            // to avoid ModelBinding updates to affect this
            // globally
            return mealTypes
                .Select(d => new SelectListItem()
                {
                    Value = d.Value,
                    Text = d.Text
                })
             .ToArray();
        }
        #endregion

    }
}

FirstWebApplication/Views/UserLogin/DashBoard.cshtml
@using PagedList
@using PagedList.Mvc

@model IPagedList<MenuDetail>

@{
    ViewBag.Title = "DashBoard";
    MenuDetail menuItem = new MenuDetail();
}

@section Scripts
{
    @Styles.Render("~/Content/sliderCheckBox.css")
    @Scripts.Render("~/bundles/jqueryval")
    <link href="~/Content/menu.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/Content/ModalPopup.css" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    @if (ViewBag.deleteMessage != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                toastr.error('Item Deleted Succesfully', 'Delete Message', { timeOut: 5000 })
                
            });
        </script>
    }
    @if (ViewBag.addMessage != null)
    {
        if (ViewBag.addMessage == "Added")
        {
            <script type="text/javascript">
                $(document).ready(function () {
                    toastr.success('Item Added Succesfully', 'Success Message', { timeOut: 5000 })
                });
            </script>
        }
        else if (ViewBag.addMessage == "Error")
        {
            <script type="text/javascript">
                $(document).ready(function () {
                    toastr.warning('Error while Add', 'Warning Message', { timeOut: 5000 })
                });
            </script>
        }
    }
    @if (ViewBag.editMessage != null)
    {
        if (ViewBag.editMessage == "Edited")
        {
            <script type="text/javascript">
                $(document).ready(function () {
                    toastr.info('Item updated Succesfully', 'Update Message', { timeOut: 5000 })
                });
            </script>
        }
        else if (ViewBag.editMessage == "Error")
        {
            <script type="text/javascript">
                $(document).ready(function () {
                    toastr.warning('Error while Update', 'Warning Message', { timeOut: 5000 })
                });
            </script>
        }
    }
    <script type="text/javascript">
        $('#AddModalCenter').on('hidden.bs.modal', function () {
            var theForm = $(this).find('form');

            theForm.each(function () {
                theForm.find(".field-validation-error").empty();
                theForm.trigger('reset.unobtrusiveValidation');
            });
        })

    </script>
}


<div style="height: 100% ">

    <div class="section-header">
        <div style="display: flex; justify-content: right;">
            <h2 style="margin: auto; margin-top: 20px; font-size: 35px; color: #88ebd3ac; border-radius: 5px; text-align: center; font-weight: 650 ">Our Menu</h2>
        </div>

        <br />
        <div style="display: flex; justify-content: flex-end;height:fit-content">
            <div style="display:contents">

                <button type="button" class="btn" data-toggle="modal" data-target="#AddModalCenter" style="color: #fff;font-size: initial; margin-right: auto; height: fit-content; align-content: center; background-color: #563D7C ">
                    Add <i class="fa fa-add" style="padding:0px" aria-hidden="true"></i>
                </button>
            </div>

            <div class="modal fade" id="AddModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" style=" background: rgb(255, 255, 255,0.3)" >
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title popup-header-title" style="margin:auto" id="exampleModalLongTitle">Add MenuItem</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span class="popup-header-title" aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            @{
                                ViewBag.ActionMethod = "Add";
                                Html.RenderPartial("AddEditMenuItem", new MenuDetail());
                            }
                        </div>
                    </div>
                </div>
            </div>


            @using (Html.BeginForm("SearchFunction", "UserLogin", FormMethod.Get))
            {
                <div style="display: inline-flex;flex-direction: column; justify-content: space-evenly; align-items: flex-end;">
                    <div>
                        @Html.DropDownList("MealType", (IEnumerable<SelectListItem>)ViewBag.mealTypes, "---ALL---", new { @class = "dropdown", style = "height:26px;padding:2px;margin-top:8px" })
                        @Html.TextBox("searchString", "", new { @class = "", placeholder = "Search here...", style = "margin-top:8px;margin-bottom:8px" })
                    </div>
                    <div>
                        <button type="submit" value="register" class="btn" style="color: #fff;background-color: #563D7C; height: 22px; height: fit-content; align-content: center ">
                            Search <i class="fa fa-search fa-1x" style="padding:0px" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
                <br />

            }

        </div>

        <br />

        <div id="loadpartial">
            @{
                Html.RenderPartial("DisplayMenuItem", Model);
            }
            <div id="Paging" class="col-sm-12">
                @if (ViewBag.Action == "SearchFunction")
                {
                    @Html.PagedListPager(Model, page => Url.Action("SearchFunction", new { page, MealType = Request.QueryString["MealType"], searchString = Request.QueryString["searchString"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })
                }
                else
                {
                    @Html.PagedListPager(Model, page => Url.Action("DashBoard", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })
                }
            </div>
        </div>



    </div>
</div>

FirstWebApplication/Views/UserLogin/Index.cshtml
@model FirstWebApplication.Models.UserLogin
@{
    ViewBag.Title = "Index";
    var Message = ViewBag.Message;
}

@section scripts{
    @Styles.Render("~/Content/LoginStyle.css")

    <link href="~/Content/menu.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/Content/ModalPopup.css" />
    @if (ViewBag.ReisterMessage != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                toastr.success('Account is activated', 'Success Message', { timeOut: 5000 })
            });
        </script>
    }
    @if (ViewBag.PasswordReset != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                toastr.success('Password reset successfully', 'Success Message', { timeOut: 5000 })
            });
        </script>
    }
    <script type="text/javascript">
        $('#ForgotPassword').on('hidden.bs.modal', function () {
            var theForm = $(this).find('form');

            theForm.each(function () {
                theForm.find(".field-validation-error").empty();
                theForm.trigger('reset.unobtrusiveValidation');
            });
        })

    </script>
}

<div class="wrapper">
    <div class="logo">
        <img src="../Image/TIS.png" alt="">
    </div>
    <br />
    <div class="text-center mt-4 name">
        The Imperial Spice
    </div>
    <br />
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["ErrorMessage"]
        </div>
    }
    else if (ViewBag.ForgotPassword != null)
    {
        <div class="alert alert-success" role="alert">
            You can reset the Password with link send to your Email..
        </div>
    }
    @using (Html.BeginForm("Login", "UserLogin", FormMethod.Post))
    {
        @Html.ValidationMessageFor(s => s.UserName, "", new { @class = "text-danger" })
        <div class="form-field d-flex align-items-center" style="display : flex">
            <span style="margin:auto">
                <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            @*<input type="text" name="userName" id="userName" placeholder="Username">*@
            @Html.TextBoxFor(s => s.UserName, new { @class = "", placeholder = "Enter User name..." })
        </div>

        @Html.ValidationMessageFor(s => s.Password, "", new { @class = "text-danger" })
        <div class="form-field d-flex align-items-center" style="display : flex">
            <span class="fas fa-key" style="margin:auto"></span>
            @*<input type="password" name="password" id="pwd" placeholder="Password">*@
            @Html.PasswordFor(s => s.Password, new { @class = "", placeholder = "Enter Password..." })
        </div>

        <a href="#" data-toggle="modal" data-target="#ForgotPassword" style="font-size:15px">Forgot password?</a>

        <button type="submit" value="register" class="btn mt-3">Login</button>
    }
    <div class="text-center mt-4 name" style="display:grid">
        <span style="font-size:20px">or</span>
        <a href=@Url.Action("Index","User") style="font-size:25px">Sign up</a>
    </div>
</div>

<div class="modal fade" id="ForgotPassword" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title popup-header-title" style="margin:auto" id="exampleModalLongTitle">Forgot Password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span class="popup-header-title" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @{
                    Html.RenderPartial("ForgotPassword", new FirstWebApplication.Models.ForgotPassword());
                }
            </div>
        </div>
    </div>
</div>


@*<div style="height: 100% ">
        <h2 style="color: #000000; background: rgb(255, 255, 255,0.5); padding: 4px; width: fit-content; border: 1px solid #ccc; border-radius: 16px; ">Sign In</h2>


        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-warning" role="alert">
                @TempData["ErrorMessage"]
            </div>
        }
        @using (Html.BeginForm("Login", "UserLogin", FormMethod.Post))
        {


            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group row">

                @Html.LabelFor(l => l.UserName, new { @class = "col-sm-2 col-form-label", style = "color: #000000; background: rgb(255, 255, 255,0.5);text-align: center; border: 1px solid #ccc; border-radius: 16px; " })
                <div class="col-sm-10">
                    @Html.TextBoxFor(s => s.UserName, new { @class = "", placeholder = "Enter User name...", style = "margin-bottom : 7px" })
                    @Html.ValidationMessageFor(s => s.UserName, "", new { @class = "text-danger", style = "color: #ff0000;    background: rgb(255, 255, 255,0.5)" })
                </div>
                <br />

                @Html.LabelFor(l => l.Password, new { @class = "col-sm-2 col-form-label", style = "color: #000000; background: rgb(255, 255, 255,0.5);text-align: center; border: 1px solid #ccc; border-radius: 16px; " })
                <div class="col-sm-10">
                    @Html.PasswordFor(s => s.Password, new { @class = "", placeholder = "Enter Password...", style = "margin-bottom : 7px" })
                    @Html.ValidationMessageFor(s => s.Password, "", new { @class = "text-danger", style = "color: #ff0000;    background: rgb(255, 255, 255,0.5)" })
                </div>

                <br />

                <div style="margin-left : 160px">
                    <button type="submit" value="register" class="btn btn-primary">Login</button>
                </div>
            </div>
        }
    </div>*@